services:
  fail2ban-exporter:
    image: registry.gitlab.com/hctrdev/fail2ban-prometheus-exporter:latest
    container_name: fail2ban-exporter
    ports:
      - "9191:9191"
    volumes:
      - "/var/run/fail2ban:/var/run/fail2ban:ro"
    restart: unless-stopped
